### ISSUE TITLE
Any specifications on uploading an image for interpolation?

### ISSUE THREAD

**Issue by JettChenT** [genforce/idinvert_pytorch#10]
While I was running your notebook for interpolation, I encountered this issue:
I uploaded this image as the target image and selected the default image for source image:
![IMG_1988](https://user-images.githubusercontent.com/45888395/96873060-07546f00-14a7-11eb-9bed-3aa6ecd3a64e.png)
After performing interpolation, this happened:
![9k (1)](https://user-images.githubusercontent.com/45888395/96873145-23f0a700-14a7-11eb-8c4d-7f67c8d5d5dc.jpg)
No errors were reported throughout the process, and a similar result was produced upon trying different png files.
Any idea on what went wrong?

**Comment by zhujiapeng** [comment]
This is the failure case caused by the face detector.

**Comment by gsygsy96** [comment]
@JettChenT , could you please show the aligned target images?

**Comment by JettChenT** [comment]
@shyanguan thank you for responding. I'm new to this so could you please tell me how to do that?

**Comment by gsygsy96** [comment]
The input image should be aligned first. Have you done this step?

**Comment by JettChenT** [comment]
@shyanguan No. How do I align the input image?

**Comment by gsygsy96** [comment]
Refer to another repo, named StyleGAN-encoder.

**Comment by JettChenT** [comment]
@ShenYujun Should the aligned image look like this?
![IMG_1988_01](https://user-images.githubusercontent.com/45888395/97105807-c5226c00-16f8-11eb-921c-effb7e0fc10f.png)

**Comment by ShenYujun** [comment]
OMG, it should not look like this. Is your image with three channels? I think it happens because the pixels misalign across channels.

**Comment by JettChenT** [comment]
Thanks a lot for the support! It really helped.
