### ISSUE TITLE
pretrained discriminator

### ISSUE THREAD

**Issue by hadzica** [genforce/idinvert_pytorch#12]
Hello

For the tensorflow version the pretrained discriminator is provided. Why not for pytorch since, according to the paper, the discriminator and encoder are trained in the same time. Do you maybe still have the pretrained discriminator? Could you please share it?

Thanks

Amir

**Comment by zhujiapeng** [comment]
Wo do not use the discriminator when doing the inference tasks.

**Comment by hadzica** [comment]
I understand but since you can provide a pretrained encoder you should theoretically be able to also have the discriminator available since they are trained jointly. Otherwise I can not explain how you can provide the encoder but in the same time the discriminator not.  For a project my team and I need also the corresponding discriminator. Is it somehow possible to map the tensorflow model to a pytorch model?

**Comment by ShenYujun** [comment]
Thanks for your request! However, this repo is just **for inference with our encoder**, which is more friendly to PyTorch users. So we have not planned to provide the PyTorch version discriminator. Alternatively, you can refer to [this repo](https://github.com/genforce/idinvert) to get the TensorFlow version, then find the PyTorch implementation of the discriminator in [this repo](https://github.com/genforce/genforce), and finally convert the weight by yourselves.

**Comment by hadzica** [comment]
Okay thanks for your response. I have downloaded the tensorflow model. It is quite hard to find the locations where the weights in the dnnlib.tflib network object can be accessed. Do you have an idea?
