### ISSUE TITLE
How to get the layers of attributes for manipulation?

### ISSUE THREAD

**Issue by falloncandra** [genforce/idinvert_pytorch#21]
Hi, thanks for your work!

In the colab example, we can manipulate attributes (age, eyeglasses, gender, pose, expression). We manipulate the attributes by adding values in the dimension of `manipulate_layers`. For instance, gender is manipulated using layer [2, 3, 4], while expression is manipulated using layer [2,3,4,5]. I wonder, how did you know that a certain attribute is associated with particular layers?

Thank you very much for your help!

**Comment by zhujiapeng** [comment]
https://github.com/genforce/idinvert/issues/12

**Comment by falloncandra** [comment]
Thanks for your answer!
