### ISSUE TITLE
About the Inversion Speed in paper

### ISSUE THREAD

**Issue by tachikoma777** [genforce/idinvert_pytorch#27]
Hi, great work!
I notice that in first version the In-domain Inversion speed is 142s, but in following versions the speed is 8s.
Did you do anything to speed up? is the speed based on domain-guided encoder to provide the initialization?
Thanks!

**Comment by zhujiapeng** [comment]
Yes, we found that with the initialization of our domain-guided encoder, the number of iterations of optimization has been reduced from more than 1000 to 100. Besides, the dimension of the last feature maps of our encoder has been reduced from 4x4x1024 to 4x4x512.
