### ISSUE TITLE
Convert pretrained encoders trained using TF repository of idinvert. 

### ISSUE THREAD

**Issue by Caselles** [genforce/idinvert_pytorch#3]
Hello,

First of all, thanks for releasing the PyTorch version of the code for your paper. It's pretty useful !

I have several questions : 

1) regarding the pretrained encoder provided in the repo : is it the same model as the pretrained encoder provided in the TF repository ? If yes, do you have the code needed for converting the TF model in PyTorch ? It seems that you are using the same architecture of models as in InterfaceGAN, which provided code for TF->PyTorch conversion (for stylegan generator for instance). Having the code for converting encoders would be nice for training other encoders in TF and then doing inference in PyTorch. 

2) are you considering releasing code for training encoders also in PyTorch ? 

Thank you so much again for all the work you put in (paper and code release).

**Comment by ShenYujun** [comment]
Yes, we are currently planning to release a full-function PyTorch codebase. It should be released in around 1-1.5 months. Please be patient! Thanks for liking our work ;)

**Comment by Caselles** [comment]
Thank you very much!

**Comment by wataoka** [comment]
I'm also waiting for the release. Thank you for your work!
