### ISSUE TITLE
How can I get the vgg16.pth

### ISSUE THREAD

**Issue by Caiqiurun** [genforce/idinvert_pytorch#6]
Hello, thanks for your contribution.
I wanna know how can I get the vgg16.pth.
Thank you.

**Comment by Caiqiurun** [comment]
Sorry, I got it.

**Comment by cssddnnc9527** [comment]
@Caiqiurun Can you tell me how to get vgg16.pth? 
Thanks very much!

**Comment by Jjef2002** [comment]
can u tell how to get vgg16.pth
